- hosts: all
  become: yes
  user: centos
  gather_facts: no
  pre_tasks:
  - name: desativando o SeLinux
    selinux:
      state: disabled

  - name: desativando o Firewalld 
    yum:
      name: firewalld
      state: removed
  
  - name: desativando o swap 
    shell: swapoff -a
    
  - name: removendo o swap 
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'

  - name: 'atualizando repo'
    yum:
      update_only: latest
  
  - name: 'instalando o python'
    yum:
        name: python 
        state: latest
  
  roles:
  - { role: install-k8s, tags: ["install_k8s_role"]}

- hosts: k8s-master
  become: yes
  user: centos
  roles:
  - { role: create-cluster, tags: ["create_cluster_role"]}

- hosts: k8s-workers
  become: yes
  user: centos
  roles:
  - { role: join-workers, tags: ["join_workers_role"]}
